export { default as Text } from './Text/Text'
export type { TextStyle, TextColor, TextAlign } from './Text/Text'
export { default as Divider } from './Divider/Divider'
export { default as Table } from './Table/Table'
export type { TableColumns } from './Table/Table'
